# Generated by Django 4.1.3 on 2023-04-07 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintApp', '0006_alter_complaint_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='resident',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Resident'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
