# Generated by Django 4.1.3 on 2023-04-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintApp', '0007_alter_complaint_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ComplaintStatus',
            field=models.CharField(choices=[('Under review', 'one'), ('Being resolved', 'two'), ('Resolved', 'three')], default='Under review', max_length=50),
        ),
    ]
